In [16]:
import sys
import os
import pandas as pd

# Add the parent directory of 'app' to the Python path
sys.path.append(os.path.abspath('D:/GitHub/personal_finances_analysis'))

from src.ofx_dataprep import OfxDataPrep

# In root path we have the folders input, output and processed
root_path = "D:\GitHub\_DADOS\personal_finances"
input_path = os.path.join(root_path, "input")

In [17]:
dataprep = OfxDataPrep()
transactions = dataprep.read_and_prep_data(data_path=input_path)

In [18]:
display(type(transactions))
display(transactions.shape)
display(transactions.columns)
display(transactions.dtypes)

pandas.core.frame.DataFrame

(679, 12)

Index(['type', 'date', 'amount', 'id', 'memo', 'account_id', 'number',
       'institution', 'year', 'year_month', 'in_out', 'is_installment'],
      dtype='object')

type                 object
date                 object
amount              float64
id                   object
memo                 object
account_id           object
number               object
institution          object
year                  int32
year_month        period[M]
in_out               object
is_installment         bool
dtype: object

In [19]:
transactions.head()

,type,date,amount,id,memo,account_id,number,institution,year,year_month,in_out,is_installment
0,Credit Card,2024-12-04,-38.90,674ea97b-5319-4c30-83bf-47b17323cfe5,Cinemark Brasil,5a43cccd-bdaf-4211-a5c5-bc45326df942,5a43cccd-bdaf-4211-a5c5-bc45326df942,NU PAGAMENTOS S.A.,2024,2024-12,out,False
1,Credit Card,2024-12-02,-14.96,674b9f46-f4c2-4ff9-98f9-722110c83e69,Uber Uber *Trip Help.U,5a43cccd-bdaf-4211-a5c5-bc45326df942,5a43cccd-bdaf-4211-a5c5-bc45326df942,NU PAGAMENTOS S.A.,2024,2024-12,out,False
2,Credit Card,2024-12-02,-69.58,674c983d-2d23-4a81-9b5f-cd6f4dedbf7d,Vamo Ki Vamo,5a43cccd-bdaf-4211-a5c5-bc45326df942,5a43cccd-bdaf-4211-a5c5-bc45326df942,NU PAGAMENTOS S.A.,2024,2024-12,out,False
3,Credit Card,2024-12-02,-7.65,674cb742-4e40-4dcb-a7db-98688abb227c,Top Sp Tarif*Descripti,5a43cccd-bdaf-4211-a5c5-bc45326df942,5a43cccd-bdaf-4211-a5c5-bc45326df942,NU PAGAMENTOS S.A.,2024,2024-12,out,False
4,Credit Card,2024-12-02,-68.05,674c86d2-b258-43ce-b82e-45049ebba24a,Horti Fruti Ortencia,5a43cccd-bdaf-4211-a5c5-bc45326df942,5a43cccd-bdaf-4211-a5c5-bc45326df942,NU PAGAMENTOS S.A.,2024,2024-12,out,False

In [21]:
display(transactions['in_out'].value_counts())
display(transactions['type'].value_counts())
transactions.groupby(['year_month', 'in_out', 'type']).size().unstack().fillna(0).astype(int)

in_out
out    592
in      87
Name: count, dtype: int64

type
Credit Card    492
Bank           187
Name: count, dtype: int64

type               Bank  Credit Card
year_month in_out
2024-11    in        12            1
           out       14           66
2024-12    in        12            1
           out       15           59
2025-01    in        13            2
           out       18           73
2025-02    in         7            5
           out       17           90
2025-03    in         7            5
           out       16           73
2025-04    in         7            2
           out       15           65
2025-05    in        11            2
           out       23           43
2025-06    out        0            5

In [34]:
aux = transactions.query("in_out == 'out' and type == 'Credit Card'")['memo'].value_counts()
aux.reset_index()['memo'].to_csv('memo_credit_card.csv', encoding='utf-8', index=False)

In [24]:
transactions.query('in_out == "in" and type == "Credit Card"')['memo'].value_counts()

memo
Pagamento recebido                     7
Encerramento de dÃ­vida                6
CrÃ©dito de atraso                     2
Estorno de "Riachuelo Lo*Riachuelo"    1
Estorno de "Pg *Celetus Cltusclick"    1
Estorno de "Bp"                        1
Name: count, dtype: int64

In [ ]:
### Tipos de transações
# Cartão de Crédito
# 1. Compras no cartão de crédito = "in_out == 'out' and type == 'Credit Card'"
# 2. Estornos e pagamento da fatura do cartão de crédito = "in_out == 'in' and type == 'Credit Card'"

# Conta Corrente
# 1. Entradas, Salários = "in_out == 'in' and type == 'Bank'"
# 2. Pagamentos de Contas (Boletos, Despesas de Casa) e PIX realizados = "in_out == 'out' and type == 'Bank'"

# transactions.query("in_out == 'out' and type == 'Bank'")['memo'].value_counts()